version: '3'

networks:
  garbage-test:
    driver: bridge

services:
  garbage_test:
    build:
      context: ../
      dockerfile: ./docker/eventsvc/Dockerfile.test
    depends_on:
      - db
    networks:
      - garbage-test
    volumes:
      - $PWD:/garbage

  db:
    image: postgres:12.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    networks:
      - garbage-test
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./eventsvc/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
