// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.2
// source: schooling_service.proto

package eventsv1pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AddPupilsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// pupils to be added
	Pupils []*AddPupilsRequest_Pupil `protobuf:"bytes,1,rep,name=pupils,proto3" json:"pupils,omitempty"`
}

func (x *AddPupilsRequest) Reset() {
	*x = AddPupilsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schooling_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPupilsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPupilsRequest) ProtoMessage() {}

func (x *AddPupilsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schooling_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPupilsRequest.ProtoReflect.Descriptor instead.
func (*AddPupilsRequest) Descriptor() ([]byte, []int) {
	return file_schooling_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddPupilsRequest) GetPupils() []*AddPupilsRequest_Pupil {
	if x != nil {
		return x.Pupils
	}
	return nil
}

type AddPupilsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ids of the pupils added
	PupilIds []string `protobuf:"bytes,1,rep,name=pupil_ids,json=pupilIds,proto3" json:"pupil_ids,omitempty"`
}

func (x *AddPupilsResponse) Reset() {
	*x = AddPupilsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schooling_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPupilsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPupilsResponse) ProtoMessage() {}

func (x *AddPupilsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schooling_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPupilsResponse.ProtoReflect.Descriptor instead.
func (*AddPupilsResponse) Descriptor() ([]byte, []int) {
	return file_schooling_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddPupilsResponse) GetPupilIds() []string {
	if x != nil {
		return x.PupilIds
	}
	return nil
}

type ChangePupilClassRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PupilId string `protobuf:"bytes,1,opt,name=pupil_id,json=pupilId,proto3" json:"pupil_id,omitempty"`
	// class name as it is now (class name changes depending on the date)
	Class string `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
}

func (x *ChangePupilClassRequest) Reset() {
	*x = ChangePupilClassRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schooling_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangePupilClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePupilClassRequest) ProtoMessage() {}

func (x *ChangePupilClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schooling_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePupilClassRequest.ProtoReflect.Descriptor instead.
func (*ChangePupilClassRequest) Descriptor() ([]byte, []int) {
	return file_schooling_service_proto_rawDescGZIP(), []int{2}
}

func (x *ChangePupilClassRequest) GetPupilId() string {
	if x != nil {
		return x.PupilId
	}
	return ""
}

func (x *ChangePupilClassRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

type RemovePupilsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ids of the pupils deleted
	PupilIds []string `protobuf:"bytes,1,rep,name=pupil_ids,json=pupilIds,proto3" json:"pupil_ids,omitempty"`
}

func (x *RemovePupilsRequest) Reset() {
	*x = RemovePupilsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schooling_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePupilsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePupilsRequest) ProtoMessage() {}

func (x *RemovePupilsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schooling_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePupilsRequest.ProtoReflect.Descriptor instead.
func (*RemovePupilsRequest) Descriptor() ([]byte, []int) {
	return file_schooling_service_proto_rawDescGZIP(), []int{3}
}

func (x *RemovePupilsRequest) GetPupilIds() []string {
	if x != nil {
		return x.PupilIds
	}
	return nil
}

type AddPupilsRequest_Pupil struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// class name as it is now (class name changes depending on the date)
	Class string `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
}

func (x *AddPupilsRequest_Pupil) Reset() {
	*x = AddPupilsRequest_Pupil{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schooling_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPupilsRequest_Pupil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPupilsRequest_Pupil) ProtoMessage() {}

func (x *AddPupilsRequest_Pupil) ProtoReflect() protoreflect.Message {
	mi := &file_schooling_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPupilsRequest_Pupil.ProtoReflect.Descriptor instead.
func (*AddPupilsRequest_Pupil) Descriptor() ([]byte, []int) {
	return file_schooling_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AddPupilsRequest_Pupil) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AddPupilsRequest_Pupil) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AddPupilsRequest_Pupil) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

var File_schooling_service_proto protoreflect.FileDescriptor

var file_schooling_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x73, 0x68, 0x61, 0x6e, 0x76,
	0x6c, 0x2e, 0x67, 0x61, 0x72, 0x62, 0x61, 0x67, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7,
	0x01, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x06, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x73, 0x68, 0x61, 0x6e, 0x76, 0x6c, 0x2e, 0x67, 0x61, 0x72,
	0x62, 0x61, 0x67, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x64, 0x64, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x50, 0x75, 0x70, 0x69, 0x6c, 0x52, 0x06, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x73, 0x1a, 0x59, 0x0a,
	0x05, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x30, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x50,
	0x75, 0x70, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x4a, 0x0a, 0x17, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x32, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x50, 0x75, 0x70, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x32, 0xfb, 0x02, 0x0a, 0x10, 0x53,
	0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x7b, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x73, 0x12, 0x2a, 0x2e, 0x73,
	0x68, 0x61, 0x6e, 0x76, 0x6c, 0x2e, 0x67, 0x61, 0x72, 0x62, 0x61, 0x67, 0x65, 0x2e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x75, 0x70, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x68, 0x61, 0x6e, 0x76,
	0x6c, 0x2e, 0x67, 0x61, 0x72, 0x62, 0x61, 0x67, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x22, 0x0a, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x7f, 0x0a, 0x10,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x12, 0x31, 0x2e, 0x73, 0x68, 0x61, 0x6e, 0x76, 0x6c, 0x2e, 0x67, 0x61, 0x72, 0x62, 0x61, 0x67,
	0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x20, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1a, 0x1a, 0x15, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x73, 0x2f,
	0x7b, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x7d, 0x3a, 0x01, 0x2a, 0x12, 0x69, 0x0a,
	0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x75, 0x70, 0x69, 0x6c, 0x73, 0x12, 0x2d, 0x2e,
	0x73, 0x68, 0x61, 0x6e, 0x76, 0x6c, 0x2e, 0x67, 0x61, 0x72, 0x62, 0x61, 0x67, 0x65, 0x2e, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50,
	0x75, 0x70, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x2a, 0x0a, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x75, 0x70, 0x69, 0x6c, 0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x76, 0x31, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schooling_service_proto_rawDescOnce sync.Once
	file_schooling_service_proto_rawDescData = file_schooling_service_proto_rawDesc
)

func file_schooling_service_proto_rawDescGZIP() []byte {
	file_schooling_service_proto_rawDescOnce.Do(func() {
		file_schooling_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_schooling_service_proto_rawDescData)
	})
	return file_schooling_service_proto_rawDescData
}

var file_schooling_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_schooling_service_proto_goTypes = []interface{}{
	(*AddPupilsRequest)(nil),        // 0: shanvl.garbage.events.v1.AddPupilsRequest
	(*AddPupilsResponse)(nil),       // 1: shanvl.garbage.events.v1.AddPupilsResponse
	(*ChangePupilClassRequest)(nil), // 2: shanvl.garbage.events.v1.ChangePupilClassRequest
	(*RemovePupilsRequest)(nil),     // 3: shanvl.garbage.events.v1.RemovePupilsRequest
	(*AddPupilsRequest_Pupil)(nil),  // 4: shanvl.garbage.events.v1.AddPupilsRequest.Pupil
	(*empty.Empty)(nil),             // 5: google.protobuf.Empty
}
var file_schooling_service_proto_depIdxs = []int32{
	4, // 0: shanvl.garbage.events.v1.AddPupilsRequest.pupils:type_name -> shanvl.garbage.events.v1.AddPupilsRequest.Pupil
	0, // 1: shanvl.garbage.events.v1.SchoolingService.AddPupils:input_type -> shanvl.garbage.events.v1.AddPupilsRequest
	2, // 2: shanvl.garbage.events.v1.SchoolingService.ChangePupilClass:input_type -> shanvl.garbage.events.v1.ChangePupilClassRequest
	3, // 3: shanvl.garbage.events.v1.SchoolingService.RemovePupils:input_type -> shanvl.garbage.events.v1.RemovePupilsRequest
	1, // 4: shanvl.garbage.events.v1.SchoolingService.AddPupils:output_type -> shanvl.garbage.events.v1.AddPupilsResponse
	5, // 5: shanvl.garbage.events.v1.SchoolingService.ChangePupilClass:output_type -> google.protobuf.Empty
	5, // 6: shanvl.garbage.events.v1.SchoolingService.RemovePupils:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_schooling_service_proto_init() }
func file_schooling_service_proto_init() {
	if File_schooling_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schooling_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPupilsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schooling_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPupilsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schooling_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangePupilClassRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schooling_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePupilsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schooling_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPupilsRequest_Pupil); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schooling_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schooling_service_proto_goTypes,
		DependencyIndexes: file_schooling_service_proto_depIdxs,
		MessageInfos:      file_schooling_service_proto_msgTypes,
	}.Build()
	File_schooling_service_proto = out.File
	file_schooling_service_proto_rawDesc = nil
	file_schooling_service_proto_goTypes = nil
	file_schooling_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SchoolingServiceClient is the client API for SchoolingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchoolingServiceClient interface {
	// AddPupils adds the given pupils and returns the ids of the added
	AddPupils(ctx context.Context, in *AddPupilsRequest, opts ...grpc.CallOption) (*AddPupilsResponse, error)
	// ChangePupilClass changes the class of the pupil
	ChangePupilClass(ctx context.Context, in *ChangePupilClassRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// RemovePupils removes the pupils with the given IDs
	RemovePupils(ctx context.Context, in *RemovePupilsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type schoolingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchoolingServiceClient(cc grpc.ClientConnInterface) SchoolingServiceClient {
	return &schoolingServiceClient{cc}
}

func (c *schoolingServiceClient) AddPupils(ctx context.Context, in *AddPupilsRequest, opts ...grpc.CallOption) (*AddPupilsResponse, error) {
	out := new(AddPupilsResponse)
	err := c.cc.Invoke(ctx, "/shanvl.garbage.events.v1.SchoolingService/AddPupils", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolingServiceClient) ChangePupilClass(ctx context.Context, in *ChangePupilClassRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/shanvl.garbage.events.v1.SchoolingService/ChangePupilClass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolingServiceClient) RemovePupils(ctx context.Context, in *RemovePupilsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/shanvl.garbage.events.v1.SchoolingService/RemovePupils", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchoolingServiceServer is the server API for SchoolingService service.
type SchoolingServiceServer interface {
	// AddPupils adds the given pupils and returns the ids of the added
	AddPupils(context.Context, *AddPupilsRequest) (*AddPupilsResponse, error)
	// ChangePupilClass changes the class of the pupil
	ChangePupilClass(context.Context, *ChangePupilClassRequest) (*empty.Empty, error)
	// RemovePupils removes the pupils with the given IDs
	RemovePupils(context.Context, *RemovePupilsRequest) (*empty.Empty, error)
}

// UnimplementedSchoolingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSchoolingServiceServer struct {
}

func (*UnimplementedSchoolingServiceServer) AddPupils(context.Context, *AddPupilsRequest) (*AddPupilsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPupils not implemented")
}
func (*UnimplementedSchoolingServiceServer) ChangePupilClass(context.Context, *ChangePupilClassRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePupilClass not implemented")
}
func (*UnimplementedSchoolingServiceServer) RemovePupils(context.Context, *RemovePupilsRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePupils not implemented")
}

func RegisterSchoolingServiceServer(s *grpc.Server, srv SchoolingServiceServer) {
	s.RegisterService(&_SchoolingService_serviceDesc, srv)
}

func _SchoolingService_AddPupils_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPupilsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolingServiceServer).AddPupils(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shanvl.garbage.events.v1.SchoolingService/AddPupils",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolingServiceServer).AddPupils(ctx, req.(*AddPupilsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolingService_ChangePupilClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePupilClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolingServiceServer).ChangePupilClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shanvl.garbage.events.v1.SchoolingService/ChangePupilClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolingServiceServer).ChangePupilClass(ctx, req.(*ChangePupilClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolingService_RemovePupils_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePupilsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolingServiceServer).RemovePupils(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shanvl.garbage.events.v1.SchoolingService/RemovePupils",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolingServiceServer).RemovePupils(ctx, req.(*RemovePupilsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SchoolingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shanvl.garbage.events.v1.SchoolingService",
	HandlerType: (*SchoolingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPupils",
			Handler:    _SchoolingService_AddPupils_Handler,
		},
		{
			MethodName: "ChangePupilClass",
			Handler:    _SchoolingService_ChangePupilClass_Handler,
		},
		{
			MethodName: "RemovePupils",
			Handler:    _SchoolingService_RemovePupils_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schooling_service.proto",
}
